### ISSUE TITLE
v1.4.4 WindowsInstance relationship to KeyPair not working

### ISSUE THREAD

**Issue by 01000101** [cloudify-cosmo/cloudify-aws-plugin#215]
Building a blueprint using a WindowsInstance connected to a KeyPair doesn't seem to work as expected. It gives a `RuntimeError: Workflow failed: Task failed 'cloudify_aws.ec2.instance.start' -> Cannot locate key file` error despite having a relationship.  The same code, but using a non-Windows instance type works as expected.  

```yaml
  keypair:
    type: cloudify.aws.nodes.KeyPair
    properties:
      use_external_resource: true
      resource_id: { get_input: keypair_name }
      private_key_path: { get_input: keypair_private_key_path }
      aws_config: *provider_config

  instance:
    type: cloudify.aws.nodes.WindowsInstance
    properties:
      image_id: { get_input: instance_image }
      instance_type: { get_input: instance_flavor }
      agent_config: *windows_agent_config
      aws_config: *provider_config
    relationships:
    - type: cloudify.aws.relationships.instance_connected_to_keypair
      target: keypair
    - type: cloudify.aws.relationships.instance_connected_to_security_group
      target: security_group
    - type: cloudify.aws.relationships.instance_connected_to_subnet
      target: vpc_subnet
```

The workaround is to directly use the "start" lifecycle input as so:

```yaml
  instance:
    type: cloudify.aws.nodes.WindowsInstance
    properties:
      image_id: { get_input: instance_image }
      instance_type: { get_input: instance_flavor }
      agent_config: *windows_agent_config
      aws_config: *provider_config
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: aws.cloudify_aws.ec2.instance.start
          inputs:
            private_key_path: { get_input: keypair_private_key_path }
    relationships:
    - type: cloudify.aws.relationships.instance_connected_to_keypair
      target: keypair
    - type: cloudify.aws.relationships.instance_connected_to_security_group
      target: security_group
    - type: cloudify.aws.relationships.instance_connected_to_subnet
      target: vpc_subnet
```
