### ISSUE TITLE
Update RDS Instance Relation For Roles

### ISSUE THREAD

**Issue by mabuaisha** [cloudify-cosmo/cloudify-aws-plugin#262]
It seems that `cloudify.relationships.aws.rds.instance.connected_to` relation for role need to be updated when associating multiple roles with RDS Instance because the current code right now suppose that `iam_role_type_key` & `iam_role_id_key` should not be both exists when having relationship with RDS Instance which is wrong and need to be updated 

```
    - type: cloudify.relationships.aws.rds.instance.connected_to
      target: my_monitoring_iam_role
      source_interfaces:
        cloudify.interfaces.relationship_lifecycle:
          preconfigure:
            inputs:
              iam_role_type_key: MonitoringRoleArn
    - type: cloudify.relationships.aws.rds.instance.connected_to
      target: my_domain_iam_role
      source_interfaces:
        cloudify.interfaces.relationship_lifecycle:
          preconfigure:
            inputs:
              iam_role_type_key: DomainIAMRoleName
```
